name: flutter_local_auth
description: Local auth flutter project
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  image_picker: any
  path_provider: any

flutter:
  uses-material-design: true
